/**
 * Route catalog generator — produces ROUTES.md with all routes.
 *
 * Parses routes/web.ts for Route.get/post/put/patch/delete calls and
 * extracts: method, path, middleware, handler reference.
 *
 * Output: ROUTES.md at repo root (~200-400 tokens).
 *
 * Usage: npm run gen:routes
 */

import * as fs from 'fs';
import * as path from 'path';

const ROOT = path.resolve(__dirname, '..');
const OUTPUT = path.join(ROOT, 'ROUTES.md');
const ROUTES_FILE = path.join(ROOT, 'routes/web.ts');

interface Route {
  method: string;
  path: string;
  middleware: string[];
  handler: string;
  comment?: string;
}

function parseRoutes(): Route[] {
  const content = fs.readFileSync(ROUTES_FILE, 'utf-8');
  const lines = content.split('\n');
  const routes: Route[] = [];

  let currentComment = '';

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();

    // Track comments
    if (line.startsWith('//')) {
      currentComment = line.replace(/^\/\/\s*/, '');
      continue;
    }

    // Match: Route.get('/path', [middleware], handler)
    // or: Route.get('/path', handler)
    // or: r.get('/path', handler) inside groups
    const match = line.match(/^(?:Route|r)\.(get|post|put|patch|delete)\s*\(\s*['"`]([^'"`]+)['"`]\s*,\s*(.+)\)/);
    if (match) {
      const method = match[1].toUpperCase();
      const pathStr = match[2];
      const rest = match[3];

      // Parse middleware + handler
      // Case 1: [Auth, strictRateLimit()], handler
      // Case 2: [Auth], handler
      // Case 3: handler (no middleware)
      let middleware: string[] = [];
      let handler = rest;

      const mwMatch = rest.match(/^\[([^\]]+)\]\s*,\s*(.+)/);
      if (mwMatch) {
        middleware = mwMatch[1].split(',').map(m => m.trim().replace(/\s*as\s+.*/, '').replace(/\(\)$/, ''));
        handler = mwMatch[2];
      }

      // Clean handler (remove trailing ); or ,)
      handler = handler.replace(/[;,]\s*$/, '').trim();

      routes.push({
        method,
        path: pathStr,
        middleware: middleware.filter(m => m.length > 0),
        handler,
        comment: currentComment || undefined,
      });
      currentComment = '';
    }
  }

  return routes;
}

function formatRoutes(routes: Route[]): string {
  const lines: string[] = [];

  // Group by section (comment-based)
  let lastComment = '';

  for (const r of routes) {
    if (r.comment && r.comment !== lastComment) {
      lines.push(`### ${r.comment}`);
      lines.push('');
      lastComment = r.comment;
    }

    const mw = r.middleware.length > 0 ? ` \`${r.middleware.join(', ')}\`` : '';
    lines.push(`- \`${r.method}\` \`${r.path}\`${mw} → ${r.handler}`);
  }

  return lines.join('\n');
}

function main(): void {
  const routes = parseRoutes();

  const methods = routes.reduce((acc, r) => {
    acc[r.method] = (acc[r.method] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  const methodSummary = Object.entries(methods)
    .map(([m, c]) => `${m}: ${c}`)
    .join(', ');

  const md = `# ROUTES.md

> Auto-generated by \`npm run gen:routes\`. Do not edit manually.
> Regenerate after adding/changing routes: \`npm run gen:routes\`.
> Read this to understand the API surface in one pass.

## Stats

- Total routes: ${routes.length}
- Methods: ${methodSummary}

## Route List

${formatRoutes(routes)}
`;

  fs.writeFileSync(OUTPUT, md);
  console.log(`ROUTES.md generated: ${OUTPUT}`);
  console.log(`  ${routes.length} routes (${methodSummary})`);
}

main();
