/**
 * Schema reference generator — produces SCHEMA.md from migrations.
 *
 * Parses all migration files for CREATE TABLE and CREATE INDEX statements,
 * extracts table definitions with columns, types, constraints, and indexes.
 *
 * Output: SCHEMA.md at repo root.
 *
 * Usage: npm run gen:schema
 */

import * as fs from 'fs';
import * as path from 'path';

const ROOT = path.resolve(__dirname, '..');
const OUTPUT = path.join(ROOT, 'SCHEMA.md');
const MIGRATIONS_DIR = path.join(ROOT, 'migrations');

interface Table {
  name: string;
  columns: { name: string; type: string; constraints: string }[];
  indexes: { name: string; table: string; columns: string }[];
}

function parseMigrations(): Table[] {
  const files = fs.readdirSync(MIGRATIONS_DIR)
    .filter(f => f.endsWith('.ts'))
    .sort();

  const tables: Map<string, Table> = new Map();

  for (const file of files) {
    const content = fs.readFileSync(path.join(MIGRATIONS_DIR, file), 'utf-8');

    // Extract CREATE TABLE blocks
    const tableRegex = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(\w+)\s*\(([^;]+)\)/gi;
    let match: RegExpExecArray | null;

    while ((match = tableRegex.exec(content)) !== null) {
      const tableName = match[1];
      const body = match[2];

      // Parse columns — split by comma, but respect parentheses (for FOREIGN KEY)
      const lines: string[] = [];
      let current = '';
      let depth = 0;

      for (const char of body) {
        if (char === '(') depth++;
        if (char === ')') depth--;
        if (char === ',' && depth === 0) {
          lines.push(current.trim());
          current = '';
        } else {
          current += char;
        }
      }
      if (current.trim()) lines.push(current.trim());

      const columns: Table['columns'] = [];
      const indexes: Table['indexes'] = [];

      for (const line of lines) {
        // Skip table-level constraints (FOREIGN KEY, PRIMARY KEY at end)
        if (/^(FOREIGN\s+KEY|PRIMARY\s+KEY|UNIQUE|CHECK|CONSTRAINT)\s/i.test(line)) {
          // Extract FK info as a note
          if (/FOREIGN\s+KEY/i.test(line)) {
            const fkMatch = line.match(/FOREIGN\s+KEY\s*\(([^)]+)\)\s*REFERENCES\s+(\w+)\s*\(([^)]+)\)/i);
            if (fkMatch) {
              columns.push({
                name: fkMatch[1],
                type: `→ ${fkMatch[2]}.${fkMatch[3]}`,
                constraints: 'FOREIGN KEY',
              });
            }
          }
          continue;
        }

        // Parse column: name TYPE constraints...
        const colMatch = line.match(/^(\w+)\s+(TEXT|INTEGER|REAL|BLOB|NUMERIC|BOOLEAN|VARCHAR|CHAR|DATETIME|DATE|TIMESTAMP)(.*)$/i);
        if (colMatch) {
          columns.push({
            name: colMatch[1],
            type: colMatch[2].toUpperCase(),
            constraints: colMatch[3].trim(),
          });
        }
      }

      // Extract CREATE INDEX
      const indexRegex = /CREATE\s+INDEX\s+(?:IF\s+NOT\s+EXISTS\s+)?(\w+)\s+ON\s+(\w+)\s*\(([^)]+)\)/gi;
      let idxMatch: RegExpExecArray | null;
      while ((idxMatch = indexRegex.exec(content)) !== null) {
        indexes.push({
          name: idxMatch[1],
          table: idxMatch[2],
          columns: idxMatch[3],
        });
      }

      tables.set(tableName, { name: tableName, columns, indexes });
    }
  }

  return Array.from(tables.values());
}

function formatSchema(tables: Table[]): string {
  const sections: string[] = [];

  for (const table of tables) {
    const colLines = table.columns.map(c => {
      const constraints = c.constraints ? ` **${c.constraints}**` : '';
      return `  \`${c.name}\` ${c.type}${constraints}`;
    });

    let section = `### ${table.name}\n\n`;
    section += colLines.join('\n') + '\n';

    if (table.indexes.length > 0) {
      section += '\n**Indexes:**\n';
      for (const idx of table.indexes) {
        section += `- \`${idx.name}\` on (${idx.columns})\n`;
      }
    }

    sections.push(section);
  }

  return sections.join('\n');
}

function main(): void {
  const tables = parseMigrations();

  const md = `# SCHEMA.md

> Auto-generated by \`npm run gen:schema\`. Do not edit manually.
> Regenerate after adding migrations: \`npm run gen:schema\`.
> Read this to understand table shapes without reading 8+ migration files.

## Stats

- Tables: ${tables.length}
- Total columns: ${tables.reduce((sum, t) => sum + t.columns.length, 0)}
- Total indexes: ${tables.reduce((sum, t) => sum + t.indexes.length, 0)}

## Tables

${formatSchema(tables)}

## Relationships

\`\`\`
users ──< sessions
users ──< password_reset_tokens
users ──< assets
users ──< user_roles >── roles
roles ──< role_permissions >── permissions
\`\`\`

## Conventions

- All IDs are \`TEXT PRIMARY KEY\` (UUID v4 via \`crypto.randomUUID()\`)
- Timestamps are \`INTEGER\` (Unix epoch ms via \`Date.now()\`)
- Booleans stored as \`INTEGER\` (0/1) — SQLite.update() auto-converts
- Foreign keys use \`ON DELETE CASCADE\` unless noted
- Indexes on all foreign keys and frequently-searched columns
`;

  fs.writeFileSync(OUTPUT, md);
  console.log(`SCHEMA.md generated: ${OUTPUT}`);
  console.log(`  ${tables.length} tables, ${tables.reduce((s, t) => s + t.columns.length, 0)} columns`);
}

main();
